apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  index.html: |
    <html>
    <head><title>ENV: ARGOCD</title></head>
    <body>
    <h1>Hello, from the webserver po deployed by ARGOCD!</h1>
    </body>
    </html>