apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webserver-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "webserver-helm.labels" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "webserver-helm.labels" . }}
  template:
    metadata:
      labels:
        {{ include "webserver-helm.labels" . }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-content
        configMap:
          name: {{ .Values.configMap.name }}
