apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "webserver-helm.labels" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{ include "webserver-helm.labels" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodePortService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "webserver-helm.labels" . }}
spec:
  type: {{ .Values.nodePortService.type }}
  selector:
    {{ include "webserver-helm.labels" . }}
  ports:
    - port: {{ .Values.nodePortService.port }}
      targetPort: {{ .Values.nodePortService.targetPort }}
      nodePort: {{ .Values.nodePortService.nodePort }}
